VERSION 0.8

FROM rust:1-bullseye

WORKDIR /code

CHEF_PREPARE:
    COMMAND
    COPY --dir src Cargo.lock Cargo.toml .
    RUN cargo chef prepare --recipe-path recipe.json

BUILD:
    COMMAND
    ARG target

    RUN cargo chef cook --recipe-path recipe.json --target ${target} --release

    COPY --dir src Cargo.lock Cargo.toml .
    RUN cargo build --target ${target} --release
