VERSION 0.8

FROM rust:1-bullseye

WORKDIR /code

CHEF_PREPARE:
    FUNCTION
    COPY --dir src Cargo.lock Cargo.toml .
    RUN cargo chef prepare --recipe-path recipe.json

BUILD:
    FUNCTION
    ARG target

    RUN if [ -e recipe.json ]; then cargo chef cook --recipe-path recipe.json --target ${target} --release; fi

    COPY --dir src Cargo.lock Cargo.toml .
    RUN cargo build --target ${target} --release
